Stakeholder:
The primary stakeholder in this scenario is the Vehicle Safety Board of Chicago. They are launching a new campaign with the goal of reducing car crashes in the city.

Business Problem:
The business problem revolves around determining which car crashes are preventable and which are not. Specifically:
Preventable Crashes: These are accidents that could have easily been avoided. They typically result from factors such as not following traffic laws or negligent driving.

Less Preventable Crashes: These incidents would require substantial resources (money, time, and labor) to address. Examples include bad road conditions, vision obscurity, and adverse weather conditions.
The Vehicle Safety Board has the capacity to focus on large-scale projects, so our focus will be on the “Less Preventable” crashes that are not directly related to human error1.
Additionally, we aim to target specific age groups most involved in crashes to tailor our prevention efforts effectively

Build a classifier to predict the primary contributory cause of a car accident, given information about the car, the people in the car, the road conditions etc. You might imagine your audience as a Vehicle Safety Board who's interested in reducing traffic accidents, or as the City of Chicago who's interested in becoming aware of any interesting patterns.

This is a multi-class classification problem. You will almost certainly want to bin, trim or otherwise limit the number of target categories on which you ultimately predict. Note that some primary contributory causes have very few samples, for example.

total number of crashes for a specic period of time,
what cars  crash more (model)
what season do we have more crashes  weather/ time

possible question
.how many accidents happens each day , each month of the year
.who are the most casualities drivers or pedestrians, gender, age
.what location records most accidents
.what are the major factors causing accidents
(weather, time of the day(day/night),car make, car model, traffic control presence,condition of the traffic control, speed,ROAD_DEFECT)

In [5]:
import pandas as pd
Crashes = pd.read_csv("Traffic_Crashes_-_Crashes_20240208.csv", low_memory=False, index_col=None)
Crashes.head()

,CRASH_RECORD_ID,CRASH_DATE_EST_I,CRASH_DATE,POSTED_SPEED_LIMIT,TRAFFIC_CONTROL_DEVICE,DEVICE_CONDITION,WEATHER_CONDITION,LIGHTING_CONDITION,FIRST_CRASH_TYPE,TRAFFICWAY_TYPE,...,INJURIES_NON_INCAPACITATING,INJURIES_REPORTED_NOT_EVIDENT,INJURIES_NO_INDICATION,INJURIES_UNKNOWN,CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_MONTH,LATITUDE,LONGITUDE,LOCATION
0,6c1659069e9c6285a650e70d6f9b574ed5f64c12888479...,NaN,08/18/2023 12:50:00 PM,15,OTHER,FUNCTIONING PROPERLY,CLEAR,DAYLIGHT,REAR END,OTHER,...,1.0,0.0,1.0,0.0,12,6,8,NaN,NaN,NaN
1,5f54a59fcb087b12ae5b1acff96a3caf4f2d37e79f8db4...,NaN,07/29/2023 02:45:00 PM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,DAYLIGHT,PARKED MOTOR VEHICLE,DIVIDED - W/MEDIAN (NOT RAISED),...,0.0,0.0,1.0,0.0,14,7,7,41.854120,-87.665902,POINT (-87.665902342962 41.854120262952)
2,61fcb8c1eb522a6469b460e2134df3d15f82e81fd93e9c...,NaN,08/18/2023 05:58:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,PEDALCYCLIST,NOT DIVIDED,...,1.0,0.0,1.0,0.0,17,6,8,41.942976,-87.761883,POINT (-87.761883496974 41.942975745006)
3,004cd14d0303a9163aad69a2d7f341b7da2a8572b2ab33...,NaN,11/26/2019 08:38:00 AM,25,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,PEDESTRIAN,ONE-WAY,...,0.0,0.0,1.0,0.0,8,3,11,NaN,NaN,NaN
4,a1d5f0ea90897745365a4cbb06cc60329a120d89753fac...,NaN,08/18/2023 10:45:00 AM,20,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,FIXED OBJECT,OTHER,...,0.0,0.0,1.0,0.0,10,6,8,NaN,NaN,NaN

In [6]:
Crashes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 804163 entries, 0 to 804162
Data columns (total 48 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   CRASH_RECORD_ID                804163 non-null  object
 1   CRASH_DATE_EST_I               60229 non-null   object
 2   CRASH_DATE                     804163 non-null  object
 3   POSTED_SPEED_LIMIT             804163 non-null  int64
 4   TRAFFIC_CONTROL_DEVICE         804163 non-null  object
 5   DEVICE_CONDITION               804163 non-null  object
 6   WEATHER_CONDITION              804163 non-null  object
 7   LIGHTING_CONDITION             804163 non-null  object
 8   FIRST_CRASH_TYPE               804163 non-null  object
 9   TRAFFICWAY_TYPE                804163 non-null  object
 10  LANE_CNT                       199007 non-null  float64
 11  ALIGNMENT                      804163 non-null  object
 12  ROADWAY_SURFACE_COND           804163 non-null  object
 13  ROAD_DEFECT                    804163 non-null  object
 14  REPORT_TYPE                    780500 non-null  object
 15  CRASH_TYPE                     804163 non-null  object
 16  INTERSECTION_RELATED_I         184348 non-null  object
 17  NOT_RIGHT_OF_WAY_I             37115 non-null   object
 18  HIT_AND_RUN_I                  251501 non-null  object
 19  DAMAGE                         804163 non-null  object
 20  DATE_POLICE_NOTIFIED           804163 non-null  object
 21  PRIM_CONTRIBUTORY_CAUSE        804163 non-null  object
 22  SEC_CONTRIBUTORY_CAUSE         804163 non-null  object
 23  STREET_NO                      804163 non-null  int64
 24  STREET_DIRECTION               804159 non-null  object
 25  STREET_NAME                    804162 non-null  object
 26  BEAT_OF_OCCURRENCE             804158 non-null  float64
 27  PHOTOS_TAKEN_I                 10504 non-null   object
 28  STATEMENTS_TAKEN_I             17803 non-null   object
 29  DOORING_I                      2474 non-null    object
 30  WORK_ZONE_I                    4628 non-null    object
 31  WORK_ZONE_TYPE                 3591 non-null    object
 32  WORKERS_PRESENT_I              1184 non-null    object
 33  NUM_UNITS                      804163 non-null  int64
 34  MOST_SEVERE_INJURY             802392 non-null  object
 35  INJURIES_TOTAL                 802404 non-null  float64
 36  INJURIES_FATAL                 802404 non-null  float64
 37  INJURIES_INCAPACITATING        802404 non-null  float64
 38  INJURIES_NON_INCAPACITATING    802404 non-null  float64
 39  INJURIES_REPORTED_NOT_EVIDENT  802404 non-null  float64
 40  INJURIES_NO_INDICATION         802404 non-null  float64
 41  INJURIES_UNKNOWN               802404 non-null  float64
 42  CRASH_HOUR                     804163 non-null  int64
 43  CRASH_DAY_OF_WEEK              804163 non-null  int64
 44  CRASH_MONTH                    804163 non-null  int64
 45  LATITUDE                       798674 non-null  float64
 46  LONGITUDE                      798674 non-null  float64
 47  LOCATION                       798674 non-null  object
dtypes: float64(11), int64(6), object(31)
memory usage: 294.5+ MB

In [7]:
columns_drop = ['LONGITUDE','INTERSECTION_RELATED_I','NOT_RIGHT_OF_WAY_I','HIT_AND_RUN_I','LATITUDE','WORKERS_PRESENT_I','WORK_ZONE_TYPE','WORK_ZONE_I', 'DOORING_I','PHOTOS_TAKEN_I','CRASH_DATE_EST_I', 'FIRST_CRASH_TYPE','TRAFFICWAY_TYPE','LANE_CNT','ALIGNMENT','ROADWAY_SURFACE_COND','REPORT_TYPE', 'DATE_POLICE_NOTIFIED','STREET_DIRECTION','STREET_NO','BEAT_OF_OCCURRENCE','PHOTOS_TAKEN_I','INJURIES_FATAL','INJURIES_INCAPACITATING','INJURIES_NON_INCAPACITATING','INJURIES_REPORTED_NOT_EVIDENT','INJURIES_NO_INDICATION','INJURIES_UNKNOWN','STATEMENTS_TAKEN_I']
Crashes2 = Crashes.drop(columns=columns_drop)
Crashes2.head(5)

,CRASH_RECORD_ID,CRASH_DATE,POSTED_SPEED_LIMIT,TRAFFIC_CONTROL_DEVICE,DEVICE_CONDITION,WEATHER_CONDITION,LIGHTING_CONDITION,ROAD_DEFECT,CRASH_TYPE,DAMAGE,PRIM_CONTRIBUTORY_CAUSE,SEC_CONTRIBUTORY_CAUSE,STREET_NAME,NUM_UNITS,MOST_SEVERE_INJURY,INJURIES_TOTAL,CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_MONTH,LOCATION
0,6c1659069e9c6285a650e70d6f9b574ed5f64c12888479...,08/18/2023 12:50:00 PM,15,OTHER,FUNCTIONING PROPERLY,CLEAR,DAYLIGHT,NO DEFECTS,INJURY AND / OR TOW DUE TO CRASH,"OVER $1,500",FOLLOWING TOO CLOSELY,DISTRACTION - FROM INSIDE VEHICLE,OHARE ST,2,NONINCAPACITATING INJURY,1.0,12,6,8,NaN
1,5f54a59fcb087b12ae5b1acff96a3caf4f2d37e79f8db4...,07/29/2023 02:45:00 PM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,DAYLIGHT,NO DEFECTS,NO INJURY / DRIVE AWAY,"OVER $1,500",FAILING TO REDUCE SPEED TO AVOID CRASH,"OPERATING VEHICLE IN ERRATIC, RECKLESS, CARELE...",ASHLAND AVE,4,NO INDICATION OF INJURY,0.0,14,7,7,POINT (-87.665902342962 41.854120262952)
2,61fcb8c1eb522a6469b460e2134df3d15f82e81fd93e9c...,08/18/2023 05:58:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,NO DEFECTS,INJURY AND / OR TOW DUE TO CRASH,"$501 - $1,500",FAILING TO REDUCE SPEED TO AVOID CRASH,UNABLE TO DETERMINE,LONG AVE,2,NONINCAPACITATING INJURY,1.0,17,6,8,POINT (-87.761883496974 41.942975745006)
3,004cd14d0303a9163aad69a2d7f341b7da2a8572b2ab33...,11/26/2019 08:38:00 AM,25,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,NO DEFECTS,INJURY AND / OR TOW DUE TO CRASH,"OVER $1,500",UNABLE TO DETERMINE,NOT APPLICABLE,TERMINAL ST,2,FATAL,1.0,8,3,11,NaN
4,a1d5f0ea90897745365a4cbb06cc60329a120d89753fac...,08/18/2023 10:45:00 AM,20,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,NO DEFECTS,NO INJURY / DRIVE AWAY,"OVER $1,500",FOLLOWING TOO CLOSELY,DRIVING SKILLS/KNOWLEDGE/EXPERIENCE,TERMINAL ST,1,NO INDICATION OF INJURY,0.0,10,6,8,NaN

In [14]:
Crashes2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 804163 entries, 0 to 804162
Data columns (total 20 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   CRASH_RECORD_ID          804163 non-null  object
 1   CRASH_DATE               804163 non-null  object
 2   POSTED_SPEED_LIMIT       804163 non-null  int64
 3   TRAFFIC_CONTROL_DEVICE   804163 non-null  object
 4   DEVICE_CONDITION         804163 non-null  object
 5   WEATHER_CONDITION        804163 non-null  object
 6   LIGHTING_CONDITION       804163 non-null  object
 7   ROAD_DEFECT              804163 non-null  object
 8   CRASH_TYPE               804163 non-null  object
 9   DAMAGE                   804163 non-null  object
 10  PRIM_CONTRIBUTORY_CAUSE  804163 non-null  object
 11  SEC_CONTRIBUTORY_CAUSE   804163 non-null  object
 12  STREET_NAME              804162 non-null  object
 13  NUM_UNITS                804163 non-null  int64
 14  MOST_SEVERE_INJURY       802392 non-null  object
 15  INJURIES_TOTAL           802404 non-null  float64
 16  CRASH_HOUR               804163 non-null  int64
 17  CRASH_DAY_OF_WEEK        804163 non-null  int64
 18  CRASH_MONTH              804163 non-null  int64
 19  LOCATION                 798674 non-null  object
dtypes: float64(1), int64(5), object(14)
memory usage: 122.7+ MB

In [15]:
Crashes3 = Crashes2.dropna(subset = ['LOCATION'])

In [16]:
Crashes3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 798674 entries, 1 to 804162
Data columns (total 20 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   CRASH_RECORD_ID          798674 non-null  object
 1   CRASH_DATE               798674 non-null  object
 2   POSTED_SPEED_LIMIT       798674 non-null  int64
 3   TRAFFIC_CONTROL_DEVICE   798674 non-null  object
 4   DEVICE_CONDITION         798674 non-null  object
 5   WEATHER_CONDITION        798674 non-null  object
 6   LIGHTING_CONDITION       798674 non-null  object
 7   ROAD_DEFECT              798674 non-null  object
 8   CRASH_TYPE               798674 non-null  object
 9   DAMAGE                   798674 non-null  object
 10  PRIM_CONTRIBUTORY_CAUSE  798674 non-null  object
 11  SEC_CONTRIBUTORY_CAUSE   798674 non-null  object
 12  STREET_NAME              798674 non-null  object
 13  NUM_UNITS                798674 non-null  int64
 14  MOST_SEVERE_INJURY       796915 non-null  object
 15  INJURIES_TOTAL           796927 non-null  float64
 16  CRASH_HOUR               798674 non-null  int64
 17  CRASH_DAY_OF_WEEK        798674 non-null  int64
 18  CRASH_MONTH              798674 non-null  int64
 19  LOCATION                 798674 non-null  object
dtypes: float64(1), int64(5), object(14)
memory usage: 128.0+ MB

In [43]:
Vehicles = pd.read_csv("Traffic_Crashes_-_Vehicles_20240208.csv", low_memory=False, index_col=None)
Vehicles.head()

,CRASH_UNIT_ID,CRASH_RECORD_ID,CRASH_DATE,UNIT_NO,UNIT_TYPE,NUM_PASSENGERS,VEHICLE_ID,CMRC_VEH_I,MAKE,MODEL,...,TRAILER1_LENGTH,TRAILER2_LENGTH,TOTAL_VEHICLE_LENGTH,AXLE_CNT,VEHICLE_CONFIG,CARGO_BODY_TYPE,LOAD_TYPE,HAZMAT_OUT_OF_SERVICE_I,MCS_OUT_OF_SERVICE_I,HAZMAT_CLASS
0,1727162,f5943b05f46b8d4148a63b7506a59113eae0cf1075aabc...,12/21/2023 08:57:00 AM,2,PEDESTRIAN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1717556,7b1763088507f77e0e552c009a6bf89a4d6330c7527706...,12/06/2023 03:24:00 PM,1,DRIVER,NaN,1634931.0,NaN,NISSAN,SENTRA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1717574,2603ff5a88f0b9b54576934c5ed4e4a64e8278e005687b...,12/06/2023 04:00:00 PM,2,DRIVER,NaN,1634978.0,NaN,CHRYSLER,SEBRING,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1717579,a52ef70e33d468b855b5be44e8638a564434dcf99c0edf...,12/06/2023 04:30:00 PM,1,DRIVER,NaN,1634948.0,NaN,SUBARU,OUTBACK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1720118,609055f4b1a72a44d6ec40ba9036cefd7c1287a755eb6c...,12/10/2023 12:12:00 PM,1,DRIVER,NaN,1637401.0,NaN,TOYOTA,RAV4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
Vehicles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1640449 entries, 0 to 1640448
Data columns (total 71 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   CRASH_UNIT_ID             1640449 non-null  int64
 1   CRASH_RECORD_ID           1640449 non-null  object
 2   CRASH_DATE                1640449 non-null  object
 3   UNIT_NO                   1640449 non-null  int64
 4   UNIT_TYPE                 1638343 non-null  object
 5   NUM_PASSENGERS            242654 non-null   float64
 6   VEHICLE_ID                1602902 non-null  float64
 7   CMRC_VEH_I                30550 non-null    object
 8   MAKE                      1602897 non-null  object
 9   MODEL                     1602752 non-null  object
 10  LIC_PLATE_STATE           1455956 non-null  object
 11  VEHICLE_YEAR              1344942 non-null  float64
 12  VEHICLE_DEFECT            1602902 non-null  object
 13  VEHICLE_TYPE              1602902 non-null  object
 14  VEHICLE_USE               1602902 non-null  object
 15  TRAVEL_DIRECTION          1602902 non-null  object
 16  MANEUVER                  1602902 non-null  object
 17  TOWED_I                   203131 non-null   object
 18  FIRE_I                    1345 non-null     object
 19  OCCUPANT_CNT              1602902 non-null  float64
 20  EXCEED_SPEED_LIMIT_I      2397 non-null     object
 21  TOWED_BY                  152667 non-null   object
 22  TOWED_TO                  93817 non-null    object
 23  AREA_00_I                 56595 non-null    object
 24  AREA_01_I                 438099 non-null   object
 25  AREA_02_I                 260482 non-null   object
 26  AREA_03_I                 157036 non-null   object
 27  AREA_04_I                 156702 non-null   object
 28  AREA_05_I                 243488 non-null   object
 29  AREA_06_I                 256265 non-null   object
 30  AREA_07_I                 236683 non-null   object
 31  AREA_08_I                 234445 non-null   object
 32  AREA_09_I                 109088 non-null   object
 33  AREA_10_I                 158740 non-null   object
 34  AREA_11_I                 307985 non-null   object
 35  AREA_12_I                 301586 non-null   object
 36  AREA_99_I                 184749 non-null   object
 37  FIRST_CONTACT_POINT       1599790 non-null  object
 38  CMV_ID                    16757 non-null    float64
 39  USDOT_NO                  9436 non-null     object
 40  CCMC_NO                   2011 non-null     object
 41  ILCC_NO                   1391 non-null     object
 42  COMMERCIAL_SRC            11155 non-null    object
 43  GVWR                      9356 non-null     object
 44  CARRIER_NAME              16017 non-null    object
 45  CARRIER_STATE             15031 non-null    object
 46  CARRIER_CITY              14744 non-null    object
 47  HAZMAT_PLACARDS_I         324 non-null      object
 48  HAZMAT_NAME               59 non-null       object
 49  UN_NO                     565 non-null      object
 50  HAZMAT_PRESENT_I          12224 non-null    object
 51  HAZMAT_REPORT_I           11883 non-null    object
 52  HAZMAT_REPORT_NO          1 non-null        object
 53  MCS_REPORT_I              11931 non-null    object
 54  MCS_REPORT_NO             7 non-null        object
 55  HAZMAT_VIO_CAUSE_CRASH_I  12046 non-null    object
 56  MCS_VIO_CAUSE_CRASH_I     11841 non-null    object
 57  IDOT_PERMIT_NO            909 non-null      object
 58  WIDE_LOAD_I               146 non-null      object
 59  TRAILER1_WIDTH            2880 non-null     object
 60  TRAILER2_WIDTH            342 non-null      object
 61  TRAILER1_LENGTH           2328 non-null     float64
 62  TRAILER2_LENGTH           67 non-null       float64
 63  TOTAL_VEHICLE_LENGTH      2834 non-null     float64
 64  AXLE_CNT                  4247 non-null     float64
 65  VEHICLE_CONFIG            13890 non-null    object
 66  CARGO_BODY_TYPE           13270 non-null    object
 67  LOAD_TYPE                 12692 non-null    object
 68  HAZMAT_OUT_OF_SERVICE_I   11534 non-null    object
 69  MCS_OUT_OF_SERVICE_I      11784 non-null    object
 70  HAZMAT_CLASS              1081 non-null     object
dtypes: float64(9), int64(2), object(60)
memory usage: 888.6+ MB

In [51]:
columns_drop = ['HAZMAT_CLASS','MCS_OUT_OF_SERVICE_I','HAZMAT_OUT_OF_SERVICE_I','LOAD_TYPE','CARGO_BODY_TYPE','VEHICLE_CONFIG','AXLE_CNT','TOTAL_VEHICLE_LENGTH','TRAILER2_LENGTH','TRAILER1_LENGTH','TRAILER2_WIDTH','TRAILER1_WIDTH','WIDE_LOAD_I','IDOT_PERMIT_NO','MCS_VIO_CAUSE_CRASH_I','HAZMAT_VIO_CAUSE_CRASH_I','MCS_REPORT_NO','MCS_REPORT_I','HAZMAT_REPORT_NO','HAZMAT_REPORT_I','HAZMAT_PRESENT_I','UN_NO','HAZMAT_NAME','HAZMAT_PLACARDS_I','CARRIER_CITY','CARRIER_STATE','CARRIER_NAME','GVWR','COMMERCIAL_SRC','ILCC_NO','CCMC_NO','USDOT_NO','CMV_ID','EXCEED_SPEED_LIMIT_I','TOWED_BY','TOWED_TO', 'AREA_00_I','AREA_01_I','AREA_02_I','AREA_03_I','AREA_04_I','AREA_05_I','AREA_06_I','AREA_07_I','AREA_08_I','AREA_09_I','AREA_10_I','AREA_11_I','AREA_12_I','AREA_99_I','FIRE_I','TRAVEL_DIRECTION','LIC_PLATE_STATE','CMRC_VEH_I','NUM_PASSENGERS','CRASH_UNIT_ID','TOWED_I']
Vehicles2 = Vehicles.drop(columns=columns_drop)
Vehicles2.head(5)

,CRASH_RECORD_ID,CRASH_DATE,UNIT_NO,UNIT_TYPE,VEHICLE_ID,MAKE,MODEL,VEHICLE_YEAR,VEHICLE_DEFECT,VEHICLE_TYPE,VEHICLE_USE,MANEUVER,OCCUPANT_CNT,FIRST_CONTACT_POINT
0,f5943b05f46b8d4148a63b7506a59113eae0cf1075aabc...,12/21/2023 08:57:00 AM,2,PEDESTRIAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,7b1763088507f77e0e552c009a6bf89a4d6330c7527706...,12/06/2023 03:24:00 PM,1,DRIVER,1634931.0,NISSAN,SENTRA,2009.0,UNKNOWN,UNKNOWN/NA,UNKNOWN/NA,SLOW/STOP IN TRAFFIC,1.0,FRONT
2,2603ff5a88f0b9b54576934c5ed4e4a64e8278e005687b...,12/06/2023 04:00:00 PM,2,DRIVER,1634978.0,CHRYSLER,SEBRING,2010.0,NONE,PASSENGER,PERSONAL,PASSING/OVERTAKING,1.0,REAR-RIGHT-CORNER
3,a52ef70e33d468b855b5be44e8638a564434dcf99c0edf...,12/06/2023 04:30:00 PM,1,DRIVER,1634948.0,SUBARU,OUTBACK,2015.0,UNKNOWN,PASSENGER,PERSONAL,TURNING RIGHT,1.0,FRONT
4,609055f4b1a72a44d6ec40ba9036cefd7c1287a755eb6c...,12/10/2023 12:12:00 PM,1,DRIVER,1637401.0,TOYOTA,RAV4,2018.0,UNKNOWN,PASSENGER,PERSONAL,STRAIGHT AHEAD,1.0,SIDE-LEFT-FRONT

In [52]:
Vehicles2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1640449 entries, 0 to 1640448
Data columns (total 14 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   CRASH_RECORD_ID      1640449 non-null  object
 1   CRASH_DATE           1640449 non-null  object
 2   UNIT_NO              1640449 non-null  int64
 3   UNIT_TYPE            1638343 non-null  object
 4   VEHICLE_ID           1602902 non-null  float64
 5   MAKE                 1602897 non-null  object
 6   MODEL                1602752 non-null  object
 7   VEHICLE_YEAR         1344942 non-null  float64
 8   VEHICLE_DEFECT       1602902 non-null  object
 9   VEHICLE_TYPE         1602902 non-null  object
 10  VEHICLE_USE          1602902 non-null  object
 11  MANEUVER             1602902 non-null  object
 12  OCCUPANT_CNT         1602902 non-null  float64
 13  FIRST_CONTACT_POINT  1599790 non-null  object
dtypes: float64(3), int64(1), object(10)
memory usage: 175.2+ MB

In [54]:
Vehicles3 = Vehicles2.dropna(subset = ['VEHICLE_YEAR'])

In [56]:
Vehicles3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1344942 entries, 1 to 1640447
Data columns (total 14 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   CRASH_RECORD_ID      1344942 non-null  object
 1   CRASH_DATE           1344942 non-null  object
 2   UNIT_NO              1344942 non-null  int64
 3   UNIT_TYPE            1344932 non-null  object
 4   VEHICLE_ID           1344942 non-null  float64
 5   MAKE                 1344937 non-null  object
 6   MODEL                1344805 non-null  object
 7   VEHICLE_YEAR         1344942 non-null  float64
 8   VEHICLE_DEFECT       1344942 non-null  object
 9   VEHICLE_TYPE         1344942 non-null  object
 10  VEHICLE_USE          1344942 non-null  object
 11  MANEUVER             1344942 non-null  object
 12  OCCUPANT_CNT         1344942 non-null  float64
 13  FIRST_CONTACT_POINT  1342239 non-null  object
dtypes: float64(3), int64(1), object(10)
memory usage: 153.9+ MB

In [17]:
People = pd.read_csv("Traffic_Crashes_-_People_20240208.csv", low_memory=False, index_col=None)
People.head()

,PERSON_ID,PERSON_TYPE,CRASH_RECORD_ID,VEHICLE_ID,CRASH_DATE,SEAT_NO,CITY,STATE,ZIPCODE,SEX,...,EMS_RUN_NO,DRIVER_ACTION,DRIVER_VISION,PHYSICAL_CONDITION,PEDPEDAL_ACTION,PEDPEDAL_VISIBILITY,PEDPEDAL_LOCATION,BAC_RESULT,BAC_RESULT VALUE,CELL_PHONE_USE
0,O749947,DRIVER,81dc0de2ed92aa62baccab641fa377be7feb1cc47e6554...,834816.0,09/28/2019 03:30:00 AM,NaN,CHICAGO,IL,60651,M,...,NaN,UNKNOWN,UNKNOWN,UNKNOWN,NaN,NaN,NaN,TEST NOT OFFERED,NaN,NaN
1,O871921,DRIVER,af84fb5c8d996fcd3aefd36593c3a02e6e7509eeb27568...,827212.0,04/13/2020 10:50:00 PM,NaN,CHICAGO,IL,60620,M,...,NaN,NONE,NOT OBSCURED,NORMAL,NaN,NaN,NaN,TEST NOT OFFERED,NaN,NaN
2,O10018,DRIVER,71162af7bf22799b776547132ebf134b5b438dcf3dac6b...,9579.0,11/01/2015 05:00:00 AM,NaN,NaN,NaN,NaN,X,...,NaN,IMPROPER BACKING,UNKNOWN,UNKNOWN,NaN,NaN,NaN,TEST NOT OFFERED,NaN,NaN
3,O10038,DRIVER,c21c476e2ccc41af550b5d858d22aaac4ffc88745a1700...,9598.0,11/01/2015 08:00:00 AM,NaN,NaN,NaN,NaN,X,...,NaN,UNKNOWN,UNKNOWN,UNKNOWN,NaN,NaN,NaN,TEST NOT OFFERED,NaN,NaN
4,O10039,DRIVER,eb390a4c8e114c69488f5fb8a097fe629f5a92fd528cf4...,9600.0,11/01/2015 10:15:00 AM,NaN,NaN,NaN,NaN,X,...,NaN,UNKNOWN,UNKNOWN,UNKNOWN,NaN,NaN,NaN,TEST NOT OFFERED,NaN,NaN

In [24]:
People.shape

(1765148, 29)

In [18]:
People.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1765148 entries, 0 to 1765147
Data columns (total 29 columns):
 #   Column                 Dtype
---  ------                 -----
 0   PERSON_ID              object
 1   PERSON_TYPE            object
 2   CRASH_RECORD_ID        object
 3   VEHICLE_ID             float64
 4   CRASH_DATE             object
 5   SEAT_NO                float64
 6   CITY                   object
 7   STATE                  object
 8   ZIPCODE                object
 9   SEX                    object
 10  AGE                    float64
 11  DRIVERS_LICENSE_STATE  object
 12  DRIVERS_LICENSE_CLASS  object
 13  SAFETY_EQUIPMENT       object
 14  AIRBAG_DEPLOYED        object
 15  EJECTION               object
 16  INJURY_CLASSIFICATION  object
 17  HOSPITAL               object
 18  EMS_AGENCY             object
 19  EMS_RUN_NO             object
 20  DRIVER_ACTION          object
 21  DRIVER_VISION          object
 22  PHYSICAL_CONDITION     object
 23  PEDPEDAL_ACTION        object
 24  PEDPEDAL_VISIBILITY    object
 25  PEDPEDAL_LOCATION      object
 26  BAC_RESULT             object
 27  BAC_RESULT VALUE       float64
 28  CELL_PHONE_USE         object
dtypes: float64(4), object(25)
memory usage: 390.5+ MB

In [19]:
#get the count of null values in each column:
null_summary = People.isnull().sum()
data_types = People.dtypes
# Combine null values and data types into a summary DataFrame
summary_People = pd.DataFrame({'Null Values': null_summary, 'Data Types': data_types})
print(summary_People)

                       Null Values Data Types
PERSON_ID                        0     object
PERSON_TYPE                      0     object
CRASH_RECORD_ID                  0     object
VEHICLE_ID                   35294    float64
CRASH_DATE                       0     object
SEAT_NO                    1408309    float64
CITY                        479735     object
STATE                       461035     object
ZIPCODE                     586327     object
SEX                          29048     object
AGE                         515185    float64
DRIVERS_LICENSE_STATE       730369     object
DRIVERS_LICENSE_CLASS       898888     object
SAFETY_EQUIPMENT              4924     object
AIRBAG_DEPLOYED              33947     object
EJECTION                     21835     object
INJURY_CLASSIFICATION          718     object
HOSPITAL                   1471525     object
EMS_AGENCY                 1583351     object
EMS_RUN_NO                 1735026     object
DRIVER_ACTION               360007     object
DRIVER_VISION               360529     object
PHYSICAL_CONDITION          359047     object
PEDPEDAL_ACTION            1731573     object
PEDPEDAL_VISIBILITY        1731636     object
PEDPEDAL_LOCATION          1731576     object
BAC_RESULT                  359026     object
BAC_RESULT VALUE           1763160    float64
CELL_PHONE_USE             1763989     object

In [28]:
columns_drop = ['CELL_PHONE_USE','BAC_RESULT VALUE','BAC_RESULT','PEDPEDAL_LOCATION','PEDPEDAL_VISIBILITY','PEDPEDAL_ACTION','EMS_RUN_NO','EMS_AGENCY','HOSPITAL','SEAT_NO','VEHICLE_ID','ZIPCODE']
People2 = People.drop(columns=columns_drop)
People2.head(5)

,PERSON_ID,PERSON_TYPE,CRASH_RECORD_ID,CRASH_DATE,CITY,STATE,SEX,AGE,DRIVERS_LICENSE_STATE,DRIVERS_LICENSE_CLASS,SAFETY_EQUIPMENT,AIRBAG_DEPLOYED,EJECTION,INJURY_CLASSIFICATION,DRIVER_ACTION,DRIVER_VISION,PHYSICAL_CONDITION
0,O749947,DRIVER,81dc0de2ed92aa62baccab641fa377be7feb1cc47e6554...,09/28/2019 03:30:00 AM,CHICAGO,IL,M,25.0,IL,D,NONE PRESENT,DEPLOYMENT UNKNOWN,NONE,NO INDICATION OF INJURY,UNKNOWN,UNKNOWN,UNKNOWN
1,O871921,DRIVER,af84fb5c8d996fcd3aefd36593c3a02e6e7509eeb27568...,04/13/2020 10:50:00 PM,CHICAGO,IL,M,37.0,IL,NaN,SAFETY BELT USED,DID NOT DEPLOY,NONE,NO INDICATION OF INJURY,NONE,NOT OBSCURED,NORMAL
2,O10018,DRIVER,71162af7bf22799b776547132ebf134b5b438dcf3dac6b...,11/01/2015 05:00:00 AM,NaN,NaN,X,NaN,NaN,NaN,USAGE UNKNOWN,DEPLOYMENT UNKNOWN,NONE,NO INDICATION OF INJURY,IMPROPER BACKING,UNKNOWN,UNKNOWN
3,O10038,DRIVER,c21c476e2ccc41af550b5d858d22aaac4ffc88745a1700...,11/01/2015 08:00:00 AM,NaN,NaN,X,NaN,NaN,NaN,USAGE UNKNOWN,DEPLOYMENT UNKNOWN,UNKNOWN,NO INDICATION OF INJURY,UNKNOWN,UNKNOWN,UNKNOWN
4,O10039,DRIVER,eb390a4c8e114c69488f5fb8a097fe629f5a92fd528cf4...,11/01/2015 10:15:00 AM,NaN,NaN,X,NaN,NaN,NaN,USAGE UNKNOWN,DEPLOYMENT UNKNOWN,UNKNOWN,NO INDICATION OF INJURY,UNKNOWN,UNKNOWN,UNKNOWN

In [29]:
null_summary = People2.isnull().sum()
data_types = People2.dtypes
# Combine null values and data types into a summary DataFrame
summary_People2 = pd.DataFrame({'Null Values': null_summary, 'Data Types': data_types})
print(summary_People2)

                       Null Values Data Types
PERSON_ID                        0     object
PERSON_TYPE                      0     object
CRASH_RECORD_ID                  0     object
CRASH_DATE                       0     object
CITY                        479735     object
STATE                       461035     object
SEX                          29048     object
AGE                         515185    float64
DRIVERS_LICENSE_STATE       730369     object
DRIVERS_LICENSE_CLASS       898888     object
SAFETY_EQUIPMENT              4924     object
AIRBAG_DEPLOYED              33947     object
EJECTION                     21835     object
INJURY_CLASSIFICATION          718     object
DRIVER_ACTION               360007     object
DRIVER_VISION               360529     object
PHYSICAL_CONDITION          359047     object

In [42]:
People3.shape

(805943, 17)

In [40]:
People3 = People2.dropna(subset = ['DRIVERS_LICENSE_CLASS','AGE','CITY','STATE','DRIVERS_LICENSE_STATE'])

In [41]:
null_summary = People3.isnull().sum()
data_types = People3.dtypes
# Combine null values and data types into a summary DataFrame
summary_People3 = pd.DataFrame({'Null Values': null_summary, 'Data Types': data_types})
print(summary_People3)

                       Null Values Data Types
PERSON_ID                        0     object
PERSON_TYPE                      0     object
CRASH_RECORD_ID                  0     object
CRASH_DATE                       0     object
CITY                             0     object
STATE                            0     object
SEX                              0     object
AGE                              0    float64
DRIVERS_LICENSE_STATE            0     object
DRIVERS_LICENSE_CLASS            0     object
SAFETY_EQUIPMENT                 1     object
AIRBAG_DEPLOYED                  1     object
EJECTION                         1     object
INJURY_CLASSIFICATION            0     object
DRIVER_ACTION                    0     object
DRIVER_VISION                    0     object
PHYSICAL_CONDITION               1     object

In [57]:
Crashes3.head()

,CRASH_RECORD_ID,CRASH_DATE,POSTED_SPEED_LIMIT,TRAFFIC_CONTROL_DEVICE,DEVICE_CONDITION,WEATHER_CONDITION,LIGHTING_CONDITION,ROAD_DEFECT,CRASH_TYPE,DAMAGE,PRIM_CONTRIBUTORY_CAUSE,SEC_CONTRIBUTORY_CAUSE,STREET_NAME,NUM_UNITS,MOST_SEVERE_INJURY,INJURIES_TOTAL,CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_MONTH,LOCATION
1,5f54a59fcb087b12ae5b1acff96a3caf4f2d37e79f8db4...,07/29/2023 02:45:00 PM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,DAYLIGHT,NO DEFECTS,NO INJURY / DRIVE AWAY,"OVER $1,500",FAILING TO REDUCE SPEED TO AVOID CRASH,"OPERATING VEHICLE IN ERRATIC, RECKLESS, CARELE...",ASHLAND AVE,4,NO INDICATION OF INJURY,0.0,14,7,7,POINT (-87.665902342962 41.854120262952)
2,61fcb8c1eb522a6469b460e2134df3d15f82e81fd93e9c...,08/18/2023 05:58:00 PM,30,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,NO DEFECTS,INJURY AND / OR TOW DUE TO CRASH,"$501 - $1,500",FAILING TO REDUCE SPEED TO AVOID CRASH,UNABLE TO DETERMINE,LONG AVE,2,NONINCAPACITATING INJURY,1.0,17,6,8,POINT (-87.761883496974 41.942975745006)
13,fd05285e9d273fe20cbbebf84794045828a2ba589073b6...,07/29/2023 02:30:00 PM,10,NO CONTROLS,NO CONTROLS,UNKNOWN,UNKNOWN,UNKNOWN,NO INJURY / DRIVE AWAY,"$501 - $1,500",UNABLE TO DETERMINE,NOT APPLICABLE,47TH ST,2,NO INDICATION OF INJURY,0.0,14,7,7,POINT (-87.594212812011 41.809781151018)
14,fda2491d33ac819033f4aaa7ed901120f2f6785b7e5bbb...,07/29/2023 12:50:00 AM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,DARKNESS,UNKNOWN,NO INJURY / DRIVE AWAY,"OVER $1,500",UNABLE TO DETERMINE,NOT APPLICABLE,CALIFORNIA AVE,2,NO INDICATION OF INJURY,0.0,0,7,7,POINT (-87.696642374961 41.899224596015)
20,161ff459c7fff8e1359204d1c54db502674fdfbf7036a9...,09/20/2023 12:57:00 PM,15,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,NO DEFECTS,NO INJURY / DRIVE AWAY,"OVER $1,500",IMPROPER BACKING,NOT APPLICABLE,STONY ISLAND AVE,2,NO INDICATION OF INJURY,0.0,12,4,9,POINT (-87.585945066953 41.744151639042)

In [58]:
People3.head()

,PERSON_ID,PERSON_TYPE,CRASH_RECORD_ID,CRASH_DATE,CITY,STATE,SEX,AGE,DRIVERS_LICENSE_STATE,DRIVERS_LICENSE_CLASS,SAFETY_EQUIPMENT,AIRBAG_DEPLOYED,EJECTION,INJURY_CLASSIFICATION,DRIVER_ACTION,DRIVER_VISION,PHYSICAL_CONDITION
0,O749947,DRIVER,81dc0de2ed92aa62baccab641fa377be7feb1cc47e6554...,09/28/2019 03:30:00 AM,CHICAGO,IL,M,25.0,IL,D,NONE PRESENT,DEPLOYMENT UNKNOWN,NONE,NO INDICATION OF INJURY,UNKNOWN,UNKNOWN,UNKNOWN
12,O848601,DRIVER,f25f09798b51603bde602ded37fea826fc8b7f962fc3b0...,02/23/2020 06:15:00 PM,CHICAGO,IL,F,34.0,IL,D,SAFETY BELT USED,DID NOT DEPLOY,NONE,NO INDICATION OF INJURY,UNKNOWN,NOT OBSCURED,NORMAL
13,O877654,DRIVER,e9146986f4b0884d00ff3a54da5249263b4b36c15d01ce...,04/30/2020 03:05:00 PM,CHICAGO,IL,M,53.0,IL,B,SAFETY BELT USED,DID NOT DEPLOY,NONE,NO INDICATION OF INJURY,UNKNOWN,UNKNOWN,NORMAL
17,O879680,DRIVER,49336aaca932f7935c361c892d31e01360a08133079e3a...,05/05/2020 12:20:00 PM,CHICAGO,IL,F,64.0,IL,D,SAFETY BELT USED,NOT APPLICABLE,NONE,NO INDICATION OF INJURY,NONE,NOT OBSCURED,NORMAL
18,O879685,DRIVER,cb7e25c6e63094307e5b999a8a5ec6f781a54781aeaef3...,05/05/2020 11:35:00 AM,MELROSE PARK,IL,M,33.0,IL,D,USAGE UNKNOWN,"DEPLOYED, COMBINATION",NONE,NO INDICATION OF INJURY,UNKNOWN,UNKNOWN,NORMAL

In [59]:
Vehicles3.head()

,CRASH_RECORD_ID,CRASH_DATE,UNIT_NO,UNIT_TYPE,VEHICLE_ID,MAKE,MODEL,VEHICLE_YEAR,VEHICLE_DEFECT,VEHICLE_TYPE,VEHICLE_USE,MANEUVER,OCCUPANT_CNT,FIRST_CONTACT_POINT
1,7b1763088507f77e0e552c009a6bf89a4d6330c7527706...,12/06/2023 03:24:00 PM,1,DRIVER,1634931.0,NISSAN,SENTRA,2009.0,UNKNOWN,UNKNOWN/NA,UNKNOWN/NA,SLOW/STOP IN TRAFFIC,1.0,FRONT
2,2603ff5a88f0b9b54576934c5ed4e4a64e8278e005687b...,12/06/2023 04:00:00 PM,2,DRIVER,1634978.0,CHRYSLER,SEBRING,2010.0,NONE,PASSENGER,PERSONAL,PASSING/OVERTAKING,1.0,REAR-RIGHT-CORNER
3,a52ef70e33d468b855b5be44e8638a564434dcf99c0edf...,12/06/2023 04:30:00 PM,1,DRIVER,1634948.0,SUBARU,OUTBACK,2015.0,UNKNOWN,PASSENGER,PERSONAL,TURNING RIGHT,1.0,FRONT
4,609055f4b1a72a44d6ec40ba9036cefd7c1287a755eb6c...,12/10/2023 12:12:00 PM,1,DRIVER,1637401.0,TOYOTA,RAV4,2018.0,UNKNOWN,PASSENGER,PERSONAL,STRAIGHT AHEAD,1.0,SIDE-LEFT-FRONT
5,609055f4b1a72a44d6ec40ba9036cefd7c1287a755eb6c...,12/10/2023 12:12:00 PM,2,DRIVER,1637408.0,SUBARU,OUTBACK,2019.0,NONE,PASSENGER,PERSONAL,STRAIGHT AHEAD,1.0,FRONT-LEFT-CORNER

In [62]:
# mergedcrashes = pd.merge(Crashes3,People3 on='CRASH_RECORD_ID')
mergecrashes = People3.merge(Crashes3,on='CRASH_RECORD_ID', how='left')
mergecrashes

,PERSON_ID,PERSON_TYPE,CRASH_RECORD_ID,CRASH_DATE_x,CITY,STATE,SEX,AGE,DRIVERS_LICENSE_STATE,DRIVERS_LICENSE_CLASS,...,PRIM_CONTRIBUTORY_CAUSE,SEC_CONTRIBUTORY_CAUSE,STREET_NAME,NUM_UNITS,MOST_SEVERE_INJURY,INJURIES_TOTAL,CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_MONTH,LOCATION
0,O749947,DRIVER,81dc0de2ed92aa62baccab641fa377be7feb1cc47e6554...,09/28/2019 03:30:00 AM,CHICAGO,IL,M,25.0,IL,D,...,UNABLE TO DETERMINE,NOT APPLICABLE,LARAMIE AVE,3.0,NO INDICATION OF INJURY,0.0,3.0,7.0,9.0,POINT (-87.755576950444 41.900042872883)
1,O848601,DRIVER,f25f09798b51603bde602ded37fea826fc8b7f962fc3b0...,02/23/2020 06:15:00 PM,CHICAGO,IL,F,34.0,IL,D,...,IMPROPER OVERTAKING/PASSING,UNABLE TO DETERMINE,DEVON AVE,2.0,NO INDICATION OF INJURY,0.0,18.0,1.0,2.0,POINT (-87.700128203434 41.99766204922)
2,O877654,DRIVER,e9146986f4b0884d00ff3a54da5249263b4b36c15d01ce...,04/30/2020 03:05:00 PM,CHICAGO,IL,M,53.0,IL,B,...,UNABLE TO DETERMINE,NOT APPLICABLE,CERMAK RD,2.0,NO INDICATION OF INJURY,0.0,15.0,5.0,4.0,POINT (-87.710733928594 41.851560864391)
3,O879680,DRIVER,49336aaca932f7935c361c892d31e01360a08133079e3a...,05/05/2020 12:20:00 PM,CHICAGO,IL,F,64.0,IL,D,...,IMPROPER BACKING,UNABLE TO DETERMINE,LOCKWOOD AVE,2.0,NO INDICATION OF INJURY,0.0,12.0,3.0,5.0,POINT (-87.759019512841 41.931414096945)
4,O879685,DRIVER,cb7e25c6e63094307e5b999a8a5ec6f781a54781aeaef3...,05/05/2020 11:35:00 AM,MELROSE PARK,IL,M,33.0,IL,D,...,UNABLE TO DETERMINE,NOT APPLICABLE,GRAND AVE,2.0,NO INDICATION OF INJURY,0.0,11.0,3.0,5.0,POINT (-87.72959937021 41.907558301463)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
805938,O1732072,DRIVER,704de0289ef5a573e060faa50ccab9d56206090cb7bc8e...,12/23/2023 10:00:00 AM,CHICAGO,IL,F,41.0,IL,D,...,FOLLOWING TOO CLOSELY,UNABLE TO DETERMINE,CLYBOURN AVE,2.0,NO INDICATION OF INJURY,0.0,10.0,7.0,12.0,POINT (-87.665990169748 41.922605515596)
805939,O1732172,DRIVER,46f16ef95068af41ee64f2930ad003e76b28362fdb60f5...,12/23/2023 04:00:00 AM,GLENWOOD,IL,F,32.0,IL,D,...,FOLLOWING TOO CLOSELY,DRIVING SKILLS/KNOWLEDGE/EXPERIENCE,STONY ISLAND AVE,2.0,NO INDICATION OF INJURY,0.0,4.0,7.0,12.0,POINT (-87.585945066953 41.744151639042)
805940,O1732275,DRIVER,8de0c7255ee51feac1af8cf7d909badce68565bd8b80bd...,12/23/2023 12:20:00 AM,AURORA,IL,F,30.0,IL,D,...,IMPROPER BACKING,IMPROPER BACKING,HARRISON ST,2.0,NO INDICATION OF INJURY,0.0,0.0,7.0,12.0,POINT (-87.720399628297 41.873404645345)
805941,O1734101,DRIVER,32a3545ac118b81e7196da33866ba078ca735a4ce2c699...,12/23/2023 01:20:00 PM,CHICAGO,IL,F,66.0,IL,D,...,IMPROPER OVERTAKING/PASSING,NOT APPLICABLE,WENTWORTH AVE,2.0,NO INDICATION OF INJURY,0.0,13.0,7.0,12.0,POINT (-87.630376665403 41.794915740831)
805942,O1734102,DRIVER,32a3545ac118b81e7196da33866ba078ca735a4ce2c699...,12/23/2023 01:20:00 PM,CHICAGO,IL,M,70.0,IL,D,...,IMPROPER OVERTAKING/PASSING,NOT APPLICABLE,WENTWORTH AVE,2.0,NO INDICATION OF INJURY,0.0,13.0,7.0,12.0,POINT (-87.630376665403 41.794915740831)

In [64]:
mergecrashes1 = mergecrashes.merge(Vehicles3,on='CRASH_RECORD_ID', how='left')
mergecrashes1

,PERSON_ID,PERSON_TYPE,CRASH_RECORD_ID,CRASH_DATE_x,CITY,STATE,SEX,AGE,DRIVERS_LICENSE_STATE,DRIVERS_LICENSE_CLASS,...,VEHICLE_ID,MAKE,MODEL,VEHICLE_YEAR,VEHICLE_DEFECT,VEHICLE_TYPE,VEHICLE_USE,MANEUVER,OCCUPANT_CNT,FIRST_CONTACT_POINT
0,O749947,DRIVER,81dc0de2ed92aa62baccab641fa377be7feb1cc47e6554...,09/28/2019 03:30:00 AM,CHICAGO,IL,M,25.0,IL,D,...,834816.0,HONDA,CIVIC,2016.0,UNKNOWN,PASSENGER,PERSONAL,STRAIGHT AHEAD,1.0,FRONT
1,O749947,DRIVER,81dc0de2ed92aa62baccab641fa377be7feb1cc47e6554...,09/28/2019 03:30:00 AM,CHICAGO,IL,M,25.0,IL,D,...,834819.0,TOYOTA,YARIS,2010.0,NONE,UNKNOWN/NA,PERSONAL,PARKED,0.0,ROOF
2,O749947,DRIVER,81dc0de2ed92aa62baccab641fa377be7feb1cc47e6554...,09/28/2019 03:30:00 AM,CHICAGO,IL,M,25.0,IL,D,...,834817.0,GENERAL MOTORS CORPORATION (GMC),SIERRA,2008.0,UNKNOWN,UNKNOWN/NA,UNKNOWN/NA,PARKED,0.0,ROOF
3,O848601,DRIVER,f25f09798b51603bde602ded37fea826fc8b7f962fc3b0...,02/23/2020 06:15:00 PM,CHICAGO,IL,F,34.0,IL,D,...,805348.0,"TOYOTA MOTOR COMPANY, LTD.",CAMRY,2001.0,UNKNOWN,PASSENGER,PERSONAL,MERGING,1.0,FRONT-LEFT-CORNER
4,O848601,DRIVER,f25f09798b51603bde602ded37fea826fc8b7f962fc3b0...,02/23/2020 06:15:00 PM,CHICAGO,IL,F,34.0,IL,D,...,805338.0,HYUNDAI,SONATA,2016.0,UNKNOWN,PASSENGER,PERSONAL,STRAIGHT AHEAD,1.0,REAR-RIGHT-CORNER
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1553241,O1732275,DRIVER,8de0c7255ee51feac1af8cf7d909badce68565bd8b80bd...,12/23/2023 12:20:00 AM,AURORA,IL,F,30.0,IL,D,...,1649097.0,KIA,OTHER (EXPLAIN IN NARRATIVE),2023.0,UNKNOWN,PASSENGER,PERSONAL,BACKING,1.0,REAR-LEFT-CORNER
1553242,O1734101,DRIVER,32a3545ac118b81e7196da33866ba078ca735a4ce2c699...,12/23/2023 01:20:00 PM,CHICAGO,IL,F,66.0,IL,D,...,1650885.0,LINCOLN,OTHER (EXPLAIN IN NARRATIVE),2015.0,NONE,PASSENGER,PERSONAL,PASSING/OVERTAKING,1.0,FRONT-RIGHT-CORNER
1553243,O1734101,DRIVER,32a3545ac118b81e7196da33866ba078ca735a4ce2c699...,12/23/2023 01:20:00 PM,CHICAGO,IL,F,66.0,IL,D,...,1650892.0,BUICK,OTHER (EXPLAIN IN NARRATIVE),2004.0,NONE,VAN/MINI-VAN,PERSONAL,SLOW/STOP IN TRAFFIC,1.0,SIDE-LEFT
1553244,O1734102,DRIVER,32a3545ac118b81e7196da33866ba078ca735a4ce2c699...,12/23/2023 01:20:00 PM,CHICAGO,IL,M,70.0,IL,D,...,1650885.0,LINCOLN,OTHER (EXPLAIN IN NARRATIVE),2015.0,NONE,PASSENGER,PERSONAL,PASSING/OVERTAKING,1.0,FRONT-RIGHT-CORNER
1553245,O1734102,DRIVER,32a3545ac118b81e7196da33866ba078ca735a4ce2c699...,12/23/2023 01:20:00 PM,CHICAGO,IL,M,70.0,IL,D,...,1650892.0,BUICK,OTHER (EXPLAIN IN NARRATIVE),2004.0,NONE,VAN/MINI-VAN,PERSONAL,SLOW/STOP IN TRAFFIC,1.0,SIDE-LEFT

In [65]:
mergecrashes1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1553246 entries, 0 to 1553245
Data columns (total 49 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   PERSON_ID                1553246 non-null  object
 1   PERSON_TYPE              1553246 non-null  object
 2   CRASH_RECORD_ID          1553246 non-null  object
 3   CRASH_DATE_x             1553246 non-null  object
 4   CITY                     1553246 non-null  object
 5   STATE                    1553246 non-null  object
 6   SEX                      1553246 non-null  object
 7   AGE                      1553246 non-null  float64
 8   DRIVERS_LICENSE_STATE    1553246 non-null  object
 9   DRIVERS_LICENSE_CLASS    1553246 non-null  object
 10  SAFETY_EQUIPMENT         1553244 non-null  object
 11  AIRBAG_DEPLOYED          1553245 non-null  object
 12  EJECTION                 1553245 non-null  object
 13  INJURY_CLASSIFICATION    1553246 non-null  object
 14  DRIVER_ACTION            1553246 non-null  object
 15  DRIVER_VISION            1553246 non-null  object
 16  PHYSICAL_CONDITION       1553242 non-null  object
 17  CRASH_DATE_y             1540287 non-null  object
 18  POSTED_SPEED_LIMIT       1540287 non-null  float64
 19  TRAFFIC_CONTROL_DEVICE   1540287 non-null  object
 20  DEVICE_CONDITION         1540287 non-null  object
 21  WEATHER_CONDITION        1540287 non-null  object
 22  LIGHTING_CONDITION       1540287 non-null  object
 23  ROAD_DEFECT              1540287 non-null  object
 24  CRASH_TYPE               1540287 non-null  object
 25  DAMAGE                   1540287 non-null  object
 26  PRIM_CONTRIBUTORY_CAUSE  1540287 non-null  object
 27  SEC_CONTRIBUTORY_CAUSE   1540287 non-null  object
 28  STREET_NAME              1540287 non-null  object
 29  NUM_UNITS                1540287 non-null  float64
 30  MOST_SEVERE_INJURY       1540287 non-null  object
 31  INJURIES_TOTAL           1540287 non-null  float64
 32  CRASH_HOUR               1540287 non-null  float64
 33  CRASH_DAY_OF_WEEK        1540287 non-null  float64
 34  CRASH_MONTH              1540287 non-null  float64
 35  LOCATION                 1540287 non-null  object
 36  CRASH_DATE               1543581 non-null  object
 37  UNIT_NO                  1543581 non-null  float64
 38  UNIT_TYPE                1543571 non-null  object
 39  VEHICLE_ID               1543581 non-null  float64
 40  MAKE                     1543578 non-null  object
 41  MODEL                    1543396 non-null  object
 42  VEHICLE_YEAR             1543581 non-null  float64
 43  VEHICLE_DEFECT           1543581 non-null  object
 44  VEHICLE_TYPE             1543581 non-null  object
 45  VEHICLE_USE              1543581 non-null  object
 46  MANEUVER                 1543581 non-null  object
 47  OCCUPANT_CNT             1543581 non-null  float64
 48  FIRST_CONTACT_POINT      1540505 non-null  object
dtypes: float64(11), object(38)
memory usage: 580.7+ MB

In [66]:
mergecrashes1.isna().sum()

PERSON_ID                      0
PERSON_TYPE                    0
CRASH_RECORD_ID                0
CRASH_DATE_x                   0
CITY                           0
STATE                          0
SEX                            0
AGE                            0
DRIVERS_LICENSE_STATE          0
DRIVERS_LICENSE_CLASS          0
SAFETY_EQUIPMENT               2
AIRBAG_DEPLOYED                1
EJECTION                       1
INJURY_CLASSIFICATION          0
DRIVER_ACTION                  0
DRIVER_VISION                  0
PHYSICAL_CONDITION             4
CRASH_DATE_y               12959
POSTED_SPEED_LIMIT         12959
TRAFFIC_CONTROL_DEVICE     12959
DEVICE_CONDITION           12959
WEATHER_CONDITION          12959
LIGHTING_CONDITION         12959
ROAD_DEFECT                12959
CRASH_TYPE                 12959
DAMAGE                     12959
PRIM_CONTRIBUTORY_CAUSE    12959
SEC_CONTRIBUTORY_CAUSE     12959
STREET_NAME                12959
NUM_UNITS                  12959
MOST_SEVERE_INJURY         12959
INJURIES_TOTAL             12959
CRASH_HOUR                 12959
CRASH_DAY_OF_WEEK          12959
CRASH_MONTH                12959
LOCATION                   12959
CRASH_DATE                  9665
UNIT_NO                     9665
UNIT_TYPE                   9675
VEHICLE_ID                  9665
MAKE                        9668
MODEL                       9850
VEHICLE_YEAR                9665
VEHICLE_DEFECT              9665
VEHICLE_TYPE                9665
VEHICLE_USE                 9665
MANEUVER                    9665
OCCUPANT_CNT                9665
FIRST_CONTACT_POINT        12741
dtype: int64